---
#
- name: Prepare configuration for creating domains
  tags: weblogic, weblogic-12c
  become: true
  with_items: "{{ _oracle_weblogic_domains }}"
  template:
    src: "{{ _wls_dir }}/config-weblogic.py.j2"
    dest: "{{ oracle_weblogic_bea_home }}/create_{{ item.domain_name }}.py"

- name: Create Oracle WebLogic domains in silent mode
  tags: weblogic, weblogic-12c
  when: not item.exists
  with_items: "{{ _oracle_weblogic_domains }}"
  command: "{{ oracle_weblogic_bea_home }}/oracle_common/common/bin/wlst.sh {{ oracle_weblogic_bea_home }}/create_{{ item.domain_name }}.py"
  args:
    creates: "{{ oracle_weblogic_bea_home }}/user_projects/domains/{{ item.domain_name }}"

- name: Create AdminServer security directory
  tags: weblogic, weblogic-12c
  when: not item.exists
  with_items: "{{ _oracle_weblogic_domains }}"
  file:
    path: "{{ oracle_weblogic_bea_home }}/user_projects/domains/{{ item.domain_name }}/servers/AdminServer/security"
    state: directory
    owner: "{{ oracle_weblogic_user }}"
    group: "{{ oracle_weblogic_group }}"
    mode: 0750

- name: Create AdminServer log directory
  tags: weblogic, weblogic-12c
  when: not item.exists
  with_items: "{{ _oracle_weblogic_domains }}"
  file:
    path: "{{ oracle_weblogic_bea_home }}/user_projects/domains/{{ item.domain_name }}/servers/AdminServer/logs"
    state: directory
    owner: "{{ oracle_weblogic_user }}"
    group: "{{ oracle_weblogic_group }}"
    mode: 0750

- name: Put password into boot.properties
  tags: weblogic, weblogic-12c
  when: not item.exists
  with_items: "{{ _oracle_weblogic_domains }}"
  template:
    src: boot.properties.j2
    dest: "{{ oracle_weblogic_bea_home }}/user_projects/domains/{{ item.domain_name }}/servers/AdminServer/security/boot.properties"
    owner: "{{ oracle_weblogic_user }}"
    group: "{{ oracle_weblogic_group }}"
    mode: 0640

- name: Configure NodeManager properties
  tags: weblogic, weblogic-12c
  with_nested:
    - "{{ _oracle_weblogic_domains }}"
    - [
        { regex: '^ListenAddress=', replace_with: "ListenAddress=" },
        { regex: '^ListenPort=', replace_with: 'ListenPort=%nm_port%' }
      ]
  lineinfile:
    path: "{{ oracle_weblogic_bea_home }}/user_projects/domains/{{ item[0].domain_name }}/nodemanager/nodemanager.properties"
    state: present
    regexp: "{{ item[1].regex }}"
    line: "{{ item[1].replace_with | replace( '%nm_port%', item[0].nm_port|default(oracle_weblogic_nodemanager_port) ) }}"
