---
#
- name: Prepare configuration for creating domains
  tags: weblogic
  become: true
  with_nested:
    - "{{ _oracle_weblogic_domains }}"
    - [
       { src: "{{ _oracle_weblogic_domain_template }}", prefix: create },
       { src: "weblogic-add-cluster.py.j2", prefix: add_cluster }
      ]
  template:
    src: "{{ item[1].src }}"
    dest: "{{ oracle_weblogic_bea_home }}/{{ item.1.prefix }}_{{ item.0.domain_name }}.py"
    backup: yes

- name: Create Oracle WebLogic domains in silent mode
  tags: weblogic
  when: not item.exists and oracle_weblogic_run_wlst
  with_items: "{{ _oracle_weblogic_domains }}"
  command: "{{ oracle_weblogic_bea_home }}/oracle_common/common/bin/wlst.sh {{ oracle_weblogic_bea_home }}/create_{{ item.domain_name }}.py"
  args:
    creates: "{{ oracle_weblogic_bea_home }}/user_projects/domains/{{ item.domain_name }}"
