---
#
- name: Prepare configuration for silent mode installation
  tags: weblogic
  template:
    src: "{{ _oracle_weblogic_response_template }}"
    dest: "{{ oracle_weblogic_response_file }}"

- set_fact:
    _wls_install: "{{ oracle_weblogic_java }} {{ oracle_weblogic_java_options }} -jar {{ oracle_weblogic_tmp }}/{{ oracle_weblogic_jar }} {{ oracle_weblogic_installer_options }} -silent -responseFile {{ oracle_weblogic_response_file }} -invPtrLoc {{ oracle_weblogic_inventory_loc }} -logfile {{ oracle_weblogic_tmp }}/installer.log"
  when: oracle_weblogic_version == "12c"
  tags: weblogic

- set_fact:
    _wls_install: "{{ oracle_weblogic_java }} {{ oracle_weblogic_java_options }} -jar {{ oracle_weblogic_tmp }}/{{ oracle_weblogic_jar }} {{ oracle_weblogic_installer_options }} -silent_xml {{ oracle_weblogic_response_file }} -invPtrLoc {{ oracle_weblogic_inventory_loc }} -logfile {{ oracle_weblogic_tmp }}/installer.log"
  when: oracle_weblogic_version == "11g"
  tags: weblogic

- name: Install Oracle WebLogic {{ oracle_weblogic_version }} in silent mode
  tags: weblogic
  shell: "{{ _wls_install  }}"
  args:
    creates: "{{ oracle_weblogic_bea_home }}/oraInst.loc"
