---
# tasks file for ansible-weblogic

#
# Validation of current Oracle Weblogic installation
#
- include: validate.yml
  tags:
    - weblogic
    - weblogic-domain
    - weblogic-cluster
  when: not oracle_weblogic_already_installed

- include: prepare.yml
  tags:
    - weblogic
    - weblogic-cluster
    - weblogic-domain
  become: yes
  when: not oracle_weblogic_already_installed

#
# Installation process
#
- name: Create Oracle Middleware directory
  tags: weblogic
  file:
    path: "{{ oracle_weblogic_bea_home }}"
    state: directory
    owner: "{{ oracle_weblogic_user }}"
    group: "{{ oracle_weblogic_group }}"
    mode: 0775

- include: install.yml
  tags: weblogic
  become: yes
  become_user: "{{ oracle_weblogic_user }}"
  when: not oracle_weblogic_already_installed

#
# Fix-ups
#
# Fix group
- name: Fix-up user and group for Oracle Middleware directory
  tags: weblogic
  file:
    path: "{{ oracle_weblogic_bea_home }}"
    state: directory
    owner: "{{ oracle_weblogic_user }}"
    group: "{{ oracle_weblogic_group }}"
    recurse: yes

#- include: "fix-wlst-securerandom-{{ oracle_weblogic_version }}.yml"
#  become: yes
#  become_user: "{{ oracle_weblogic_user }}"

- set_fact:
    oracle_weblogic_already_installed: true
  tags: weblogic

#
# Configure domains and Administation server
#
- include: create-domain.yml
  tags:
    - weblogic
    - weblogic-domain
  become: yes
  become_user: "{{ oracle_weblogic_user }}"
  when: oracle_weblogic_already_installed and oracle_weblogic_domains is defined

- include: configure-adminserver.yml
  tags:
    - weblogic
    - weblogic-domain
  static: yes
  become: yes
  become_user: "{{ oracle_weblogic_user }}"
  when: oracle_weblogic_already_installed and oracle_weblogic_domains is defined

- include: configure-nodemanager.yml
  tags:
    - weblogic
    - weblogic-domain
  static: yes
  become: yes
  become_user: "{{ oracle_weblogic_user }}"
  when: oracle_weblogic_already_installed and oracle_weblogic_domains is defined

#
# Set up start up system script for domains
#
- include: system-services.yml
  tags:
    - weblogic
    - weblogic-domain
  static: yes
  when: oracle_weblogic_already_installed and oracle_weblogic_domains is defined

#
# Set up OCF Corosync resourse for AdminServer
#
- include: ocf-resource.yml
  tags:
    - weblogic
    - weblogic-cluster
  static: yes
  when: oracle_weblogic_already_installed and oracle_weblogic_ocf
