---
# Deploy system services to start Oracle WebLogic server

- name: Install domain sysvinit environment files
  tags:
    - weblogic
    - weblogic-domain
  become: true
  when: oracle_weblogic_already_installed and oracle_weblogic_sysinit
  with_items: "{{ _oracle_weblogic_domains }}"
  template:
    src: service-envfile.j2
    dest: "{{ oracle_weblogic_sysconfig_dir }}/wls-{{ item.domain_name|replace( '_', '-') }}"
    backup: yes
    owner: "{{ oracle_weblogic_user }}"
    group: "{{ oracle_weblogic_group }}"
    mode: 0644

- name: Remove domain sysvinit environment files
  tags:
    - weblogic
    - weblogic-domain
  when: oracle_weblogic_already_installed and not oracle_weblogic_sysinit
  with_items: "{{ _oracle_weblogic_domains }}"
  file:
    path: "{{ oracle_weblogic_sysconfig_dir }}/wls-{{ item.domain_name|replace( '_', '-') }}"
    state: absent

- name: Install domain NodeManager services
  tags:
    - weblogic
    - weblogic-domain
  become: true
  with_items: "{{ _oracle_weblogic_domains }}"
  when: oracle_weblogic_already_installed and oracle_weblogic_sysinit and oracle_weblogic_sysinit_nodemanager
  template:
    src: "{{ _wls_dir }}/NodeManager-sysvinit.j2"
    dest: "{{ oracle_weblogic_service_dir }}/{{ item.domain_name|replace( '_', '-') }}-nm"
    backup: yes
    owner: 0
    group: 0
    mode: 0755

- name: Remove domain NodeManager services
  tags:
    - weblogic
    - weblogic-domain
  become: true
  with_items: "{{ _oracle_weblogic_domains }}"
  when: oracle_weblogic_already_installed and (not oracle_weblogic_sysinit or not oracle_weblogic_sysinit_nodemanager)
  file:
    path: "{{ oracle_weblogic_service_dir }}/{{ item.domain_name|replace( '_', '-') }}-nm"
    state: absent

- name: Ensure domain NodeManager service(s)
  tags:
    - weblogic
    - weblogic-domain
  become: true
  with_items: "{{ _oracle_weblogic_domains }}"
  when: oracle_weblogic_already_installed and oracle_weblogic_sysinit and oracle_weblogic_sysinit_nodemanager
  service:
    state: started
    enabled: true
    name: "{{ item.domain_name|replace( '_', '-') }}-nm"

- name: Install domain AdminServer services
  tags:
    - weblogic
    - weblogic-domain
  become: true
  with_items: "{{ _oracle_weblogic_domains }}"
  when: oracle_weblogic_already_installed and oracle_weblogic_sysinit and oracle_weblogic_sysinit_adminserver
  template:
    src: "{{ _wls_dir }}/AdminServer-sysvinit.j2"
    dest: "{{ oracle_weblogic_service_dir }}/{{ item.domain_name|replace( '_', '-') }}-adm"
    backup: yes
    owner: 0
    group: 0
    mode: 0755

- name: Remove domain AdminServer services
  tags:
    - weblogic
    - weblogic-domain
  become: true
  with_items: "{{ _oracle_weblogic_domains }}"
  when: oracle_weblogic_already_installed and (not oracle_weblogic_sysinit or not oracle_weblogic_sysinit_adminserver)
  file:
    path: "{{ oracle_weblogic_service_dir }}/{{ item.domain_name|replace( '_', '-') }}-adm"
    state: absent
